---
- name: Make {{ serialport }} conf from template
  tags: rootserial
  command: cp /usr/lib/systemd/system/serial-getty@.service /etc/systemd/system/serial-getty@{{ serialport }}.service
  args:
    creates: /etc/systemd/system/serial-getty@{{ serialport }}.service

- name: Add autologin to {{ serialport }} terminal
  tags: rootserial
  lineinfile: 
    name: "/etc/systemd/system/serial-getty@{{ serialport }}.service"
    regexp: '^ExecStart=-/sbin/agetty --keep-baud'
    line: 'ExecStart=-/sbin/agetty -a root --keep-baud 115200,38400,9600 %I $TERM'
    state: present
  notify: reload serial-console@{{ serialport }}

- name: Symlink our terminal-conf to use
  tags: rootserial
  file: 
    path: /etc/systemd/system/getty.target.wants/serial-getty@{{ serialport }}.service
    state: link
    src: /etc/systemd/system/serial-getty@{{ serialport }}.service



